server:
  port: 9090
  context-path: /boot

book:
  name: 《中国国家地理》

author:
  name: 鲁迅

logging:
  file: /data/logs/test.log
  level: info

spring:
  profiles:
    active: dev

#加入actuator监控模块后有些端点需要授权才能访问，这里取消授权
management:
  security:
    enabled: false

